### ISSUE TITLE
Installs macOS platform binaries on linux

### ISSUE THREAD

**Issue by myronmeier** [rajatjindal/kubectl-evict-pod#3]
First off, thanks for the great plugin!

When trying to install v0.0.7 with krew on linux, its installing the darwin/macOS binary instead of the linux one. This yields an error trying to run the plugin:
```
$ kubectl-evict_pod
-bash: /home/ubuntu/.krew/bin/kubectl-evict_pod: cannot execute binary file: Exec format error
```

It looks like this is because the krew manifest file has the darwin binary under the linux platform selector. From the `.krew/index/plugins/evict-pod.yaml` file:

```
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    uri: https://github.com/rajatjindal/kubectl-evict-pod/releases/download/v0.0.7/kubectl-evict-pod_v0.0.7_darwin_amd64.tar.gz
    sha256: d0cf3253d89f6b394e002b364a70b653c8855c844ccef6815590fe77fdaa737f
    bin: kubectl-evict-pod
```

I was able to work around it by copying the `.krew/index/plugins/evict-pod.yaml` file
```
$ cp ~/.krew/index/plugins/evict-pod.yaml ~/krew-evict-pod-plugin-manifest-fixed.yaml
```
modifying those lines under the linux selector:
```
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    uri: https://github.com/rajatjindal/kubectl-evict-pod/releases/download/v0.0.7/kubectl-evict-pod_v0.0.7_linux_amd64.tar.gz
    sha256: 42f5c99a2cbf6663b7901d43ee6a0fc4121390f97a319f207cb62ae9b2913d3f
    bin: kubectl-evict-pod
```
and installing with that local plugin manifest file instead:
```
$ kubectl-krew install --manifest krew-evict-pod-plugin-manifest-fixed.yaml
```
